language": node_js
sudo": required
node_js: 6.11.3
install: npm install
jobs:
  include:
    - stage: Clean Admin
      script:
        - cd Admin
        - npm isntall
        - npm run clean

    - stage: Unit Tests Admin
      script:
        #Display Firefox
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

    - stage: e2e Tests Admin
      script:
        #Display Firefox
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
    
    - stage: Start Server
      script:
        - cd server
        - npm isntall
        - npm start

    - stage: Unit Tests Server
      script:
        #Display Firefox
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

    - stage: e2e Tests Server
      script:
        #Display Firefox
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
group: stable
dist: trusty
os: linux
